language: java
jdk: oraclejdk8

# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify


# Create your branch
$ git checkout -b ci_config

# Add the pipeline script to git
$ git add .travis.yml

# Commit
$ git commit -m "ci: first version of the pipeline to automate unit and integration tests"

# Push
$ git push --set-upstream origin ci_config

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"
